### ISSUE TITLE
[HTWOO:Core] Fix Dialog Framework

### ISSUE THREAD

**Issue by StfBauer** [n8design/htwoo#84]
Additional style classes are needed to position sidebars correctly.

```css
.hoo-mdldialog-outer{
  box-sizing: border-box;
  border: 0;
}
```
